language: minimal

cache:
  directories:
    - $HOME/.cache/Homebrew
    - vendor/bundle

addons:
  apt:
    package:
      - build-essential
      - curl
      - file
      - git

env:
  global:
    - HOMEBREW_DEVELOPER=1
    - HOMEBREW_NO_AUTO_UPDATE=1
    - HOMEBREW_FORCE_VENDOR_RUBY=1
    - HOMEBREW_NO_INSTALL_CLEANUP=1
    - secure: 'mD0zR8CE/HqFTMdJSb8YzcI2cK8ZDMQgU/CV62mV8X8BZrwFiac+VgYoqHsIurmPvyDaticfTwv8A/i5mm+u48HGH/kWnoUNqbIlBIFWQYVZUu/Re0xCaKikclArVhbZGgXpTsi10RhHI8stfycnnGlD3+SLYhj06SanFD3Mj0tqs6oDozTWgxbP4QFuSPTslMK1D8auwKcRqp3GHkurYSKwFtlZFO/EaKlW/UR8oMh90dqUSFUa6+OKiP/8YEI2yrnEPPWszf7BQ9MEJjlUQnRkVdPh5n5op/S3iDNfYwuer6E12c/gC55FqP+0uSNK+BuQgiZVvNuYP6BQ6obuq4ucQUEMUAUc0FeZI7STgcmZ+Foe66ZTsZRk0q6jXfy//qUzXKIzJpShKolH9TQfuzsxUuNtMMiRNd6UR//8yXMSjc1AQJUYJXLw73w5yuSIfh6jm8gfLJ6LsNP2nkdG42zuZi/KgKXSVQ0hv0LaalVw13QGZRr7p46Vrm/hV6f19uMafh6Jc5fKmhAAIkJMQEbLkoxSQE39KsWOOCqfZDZJ447EhqOYRAsFCA+vE3NPnP7JyDKzwqGjrQ5kSeYt4zlVotvKrrBAnM213lqer8II94uPvfUCTgovp55Dbn0FT3TQtCBH/MLs3gAqMHl7i3n7+itEBSn2yedtCSQmBDc='

before_install:
  - sudo rm -rf /opt/pyenv $HOME/.phpenv /usr/local/clang*
  # Fix "\"config\" scripts exist outside your system or Homebrew directories."
  # warning.

  # Install Linuxbrew
  - sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
  - eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
  # Symlink the tap
  - export HOMEBREW_TAP_NAME="$TRAVIS_REPO_SLUG"
  - export HOMEBREW_TAP_DIR="$(brew --repo $HOMEBREW_TAP_NAME)"
  - rm -rf "$HOMEBREW_TAP_DIR"
  - mkdir -p $(dirname "$HOMEBREW_TAP_DIR")
  - ln -s "$TRAVIS_BUILD_DIR" "$HOMEBREW_TAP_DIR"

install:
  - make ci-deps

before_script:
  - git branch origin/master HEAD
  # Because of [1] & [2], we have to create `origin/master` manually.
  #
  # [1]: https://github.com/Homebrew/homebrew-test-bot/blob/e970dbb45db58db2243db9f8c30a3e8647c882a9/cmd/brew-test-bot.rb#L1198
  # [2]: https://stackoverflow.com/a/44036486
  - '[ ! -d Formula ] || chmod -R go-w Formula'
  # Fix "Incorrect file permissions (664)" error from `brew audit`.

script:
  - make lint
  - make test
