language: ruby
rvm: 2.0.0
sudo: false

addons:
  apt:
    package:
      - build-essential
      - curl
      - git
      - python-setuptools
      - ruby

env:
  global:
    - LINUXBREW=$HOME/.linuxbrew
    - HOMEBREW_DEVELOPER=1
    - HOMEBREW_NO_AUTO_UPDATE=1
    - secure: "mD0zR8CE/HqFTMdJSb8YzcI2cK8ZDMQgU/CV62mV8X8BZrwFiac+VgYoqHsIurmPvyDaticfTwv8A/i5mm+u48HGH/kWnoUNqbIlBIFWQYVZUu/Re0xCaKikclArVhbZGgXpTsi10RhHI8stfycnnGlD3+SLYhj06SanFD3Mj0tqs6oDozTWgxbP4QFuSPTslMK1D8auwKcRqp3GHkurYSKwFtlZFO/EaKlW/UR8oMh90dqUSFUa6+OKiP/8YEI2yrnEPPWszf7BQ9MEJjlUQnRkVdPh5n5op/S3iDNfYwuer6E12c/gC55FqP+0uSNK+BuQgiZVvNuYP6BQ6obuq4ucQUEMUAUc0FeZI7STgcmZ+Foe66ZTsZRk0q6jXfy//qUzXKIzJpShKolH9TQfuzsxUuNtMMiRNd6UR//8yXMSjc1AQJUYJXLw73w5yuSIfh6jm8gfLJ6LsNP2nkdG42zuZi/KgKXSVQ0hv0LaalVw13QGZRr7p46Vrm/hV6f19uMafh6Jc5fKmhAAIkJMQEbLkoxSQE39KsWOOCqfZDZJ447EhqOYRAsFCA+vE3NPnP7JyDKzwqGjrQ5kSeYt4zlVotvKrrBAnM213lqer8II94uPvfUCTgovp55Dbn0FT3TQtCBH/MLs3gAqMHl7i3n7+itEBSn2yedtCSQmBDc="

before_install:
  - mkdir $LINUXBREW
  - git clone https://github.com/Linuxbrew/brew.git $LINUXBREW
  - export PATH="$LINUXBREW/bin:$LINUXBREW/sbin:$PATH"
  - HOMEBREW_TAP_NAME="${TRAVIS_REPO_SLUG/homebrew-}"
  - HOMEBREW_TAP_DIR="$(brew --repo $HOMEBREW_TAP_NAME)"
  - rm -rf "$HOMEBREW_TAP_DIR"
  - mkdir -p $(dirname "$HOMEBREW_TAP_DIR")
  - ln -s "$TRAVIS_BUILD_DIR" "$HOMEBREW_TAP_DIR"
  - ulimit -n 1024

script:
  - brew test-bot
